project:
  name: CrimeGuard-AI
  version: 2.0

paths:
  raw_data: data/raw
  processed_data: data/processed
  model_dir: models
  output_dir: outputs
  logs_dir: logs

crime:
  file_name: Crime.csv

weather:
  file_name: weather.csv

training:
  epochs: 50
  batch_size: 64
  learning_rate: 0.001

model:
  num_nodes: 77
  num_features: 10
  hidden_dim: 64
  sequence_length: 7
  output_dim: 1